name: Trivy IaC Scan

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write  # ✅ Needed for SARIF/code scanning upload

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Trivy on Terraform files and export SARIF report
      uses: aquasecurity/trivy-action@0.11.2
      with:
        scan-type: config
        scan-ref: .
        format: sarif
        output: trivy-report.sarif

    - name: Upload SARIF report to GitHub
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-report.sarif



